version: '3.8'

services:
  postgres:
    image: postgres:16  # Versión específica (más estable)
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d usersdb"]
      interval: 5s

  users-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usersdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: "MiSuperClaveLargaYSeguraParaJWT123456"  # Cambiar en prod
    depends_on:
      postgres:
        condition: service_healthy  # Espera a que Postgres responda

volumes:
  postgres_data:  # Volumen para persistir datos