spring:
  config:
    activate:
      on-profile: "default"  # Se usa cuando no hay perfil activo
  application:
    name: user-service  # Nombre más corto y estándar

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: User MicroService
    version: 0.0.1
    description: Microservicio para gestión de usuarios

# Configuración común JPA (sobrescribible por perfiles)
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate  # ¡Más seguro que 'update' en prod!

# Configuración JWT base
jwt:
  expiration-ms: 3600000  # 1 hora (común a todos los entornos)