spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://${DB_HOST:}:5432/${DB_NAME:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}  # OBLIGATORIO desde variables
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000  # 5 seg timeout
      leak-detection-threshold: 60000  # 1 minuto
  jpa:
    hibernate:
      ddl-auto: validate  # Solo valida el esquema

management:
  endpoint:
    prometheus:
      enabled: true  # Métricas para monitoreo

jwt:
  secret: ${JWT_SECRET:}  # OBLIGATORIO sin valor por defecto
  expiration-ms: 86400000  # 24 horas en prod